Allow NeuralNetClassifier to fit tensor labels #802
skorch-dev/skorch pull request #803
Opened 2021-09-27 01:20 UTC by TheAutumnOfRice

Issue #802 
The original check_data method can only receive ndarray y-values because of np.unique function. Now the method is modified so that tensor y-values can be processed with torch.unique specifically.

2021-09-28 19:19 UTC, BenjaminBossan requested changes
Thanks a lot for taking this!

There are a few stylistic changes you could make and I believe that `TypeError` is more fitting here.

Another thing: For this kind of change, we should have unit tests. Here, it is a bit tricky because the current code, i.e. using `np.unique` on a torch tensor, seems to work. The test might thus require a bit of patching.

If you need help with implementing the tests, feel free to tell me and I'll help you along the way.

2021-09-28 19:19 UTC, BenjaminBossan commented on skorch/classifier.py
> +            if isinstance(y,np.ndarray):
```suggestion
            if isinstance(y, np.ndarray):
```

2021-09-28 19:19 UTC, BenjaminBossan commented on skorch/classifier.py
> +            elif isinstance(y,torch.Tensor):
```suggestion
            elif isinstance(y, torch.Tensor):
```

2021-09-28 19:19 UTC, BenjaminBossan commented on skorch/classifier.py
> +                raise ValueError(msg)
```suggestion
                raise TypeError(msg)
```

2021-09-28 19:24 UTC, BenjaminBossan commented
I see now that the change you made introduces an error elsewhere:

```python
    def test_classes_data_torch_tensor(self, net_cls, module_cls, data):
        X = torch.as_tensor(data[0])
        y = torch.as_tensor(np.arange(len(X)) % 10)
    
        net = net_cls(module_cls, max_epochs=0).fit(X, y)
>       assert (net.classes_ == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).all()
E       AttributeError: 'bool' object has no attribute 'all'
```

This is because `classes_` used to always be a numpy array but now it can be a torch tensor. Please make sure to cast the torch tensor to a numpy array (using `skorch.utils.to_numpy`).

2021-09-29 04:15 UTC, TheAutumnOfRice commented
@BenjaminBossan Thanks for your replying!

Since `skorch.utils.to_numpy` is so powerful, we just need to add `to_numpy` to the original code, and everything is done :p

When it comes to unit tests, It's my first time to be required to use them, and I have no ideas how to deal with them haha. I hope this one-line modification can pass all these tests without my efforts.

2021-09-29 21:38 UTC, BenjaminBossan commented
> Since `skorch.utils.to_numpy` is so powerful, we just need to add `to_numpy` to the original code, and everything is done :p

That's great, so this is enough to solve your original issue in #802? If so, yeah I believe we don't need extra tests :)

2021-09-30 01:12 UTC, TheAutumnOfRice commented
Yeah, that works pretty well :)

2021-10-01 01:03 UTC, merged

2021-10-01 01:03 UTC, BenjaminBossan commented
Great, thanks for your work @TheAutumnOfRice